#!/bin/sh
######## KTLINT-GRADLE HOOK START ########

CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"

if [ -z "$CHANGED_FILES" ]; then
    echo "No Kotlin staged files."
    exit 0
fi;

echo "Running ktlint over ${#CHANGED_FILES[@]} files"
##echo "${#CHANGED_FILES}"

diff=.git/unstaged-ktlint-git-hook.diff
git diff --color=never > $diff
if [ -s $diff ]; then
  git apply -R $diff
fi

./gradlew -w ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"
gradleCommandExitCode=$?

if [[ "$gradleCommandExitCode" = 0 ]]; then
  echo "No formatting issues found"
else
  echo "Formatting issues were detected, trying to fix them."
  ./gradlew -q ktlintFormat
  formatStatus=$?
  if [[ "$formatStatus" = 0 ]]; then
    echo "Format completed, continue commit"
    git add .
    gitAddCommand=$?
    if [[ "$gitAddCommand" = 0 ]]; then
      echo "git add completed"
    else
      echo "Error in git add, added manually!!"
      exit 1
    fi
    exit 0
  else
      echo "Auto formatting failed. Manual fix needed..."
      exit 1
  fi
fi

if [ -s $diff ]; then
  git apply --ignore-whitespace $diff
fi
rm $diff
unset diff

echo "Completed ktlint hook."
exit $gradleCommandExitCode
######## KTLINT-GRADLE HOOK END ########
