#!/bin/sh
######## KTLINT-GRADLE HOOK START ########

CHANGED_FILES="$(git --no-pager diff --name-status --no-color --cached | awk '$1 != "D" && $NF ~ /\.kts?$/ { print $NF }')"

if [ -z "$CHANGED_FILES" ]; then
    echo "No Kotlin staged files."
    exit 0
fi;

echo "Running ktlint over these files:"
echo "$CHANGED_FILES"

diff=.git/unstaged-ktlint-git-hook.diff
git diff --color=never > $diff
if [ -s $diff ]; then
  git apply -R $diff
fi

./gradlew ktlintCheck -PinternalKtlintGitFilter="$CHANGED_FILES"
gradleCommandExitCode=$?

if [[ "$gradleCommandExitCode" = 0 ]]; then
  echo "Sin errores de formato"
else
  echo "Errores de formato encontrados commit no hecho"
  exit 1
fi

if [ -s $diff ]; then
  git apply --ignore-whitespace $diff
fi
rm $diff
unset diff

echo "Completed ktlint hook."
exit $gradleCommandExitCode
######## KTLINT-GRADLE HOOK END ########
